### ISSUE TITLE
Is there a compiled version?

### ISSUE THREAD

**Issue by Chrischan66** [Kaidrick/DCS-External-Camera-Interaction-System#9]
Can´t get it to work. Cheers!

**Comment by Kaidrick** [comment]
The compiled executable can be found here at the release section https://github.com/Kaidrick/DCS-External-Camera-Interaction-System/releases/tag/0.0.4

You just download the zip, extract it and run the compiled exe file. You also need to add lua files to DCS write path as per instructed in the project readme file. There is no auto script install feature for now.

Do beware this is considered experimental and feature incomplete, but nowadays my work has strafed from developing Windows desktop software, so I am afraid at least for now it can only be used as it is in the current state, until I finish the majority of work on another project.

It should work alright if configuration is done right though, recently tested.

If it somehow broke your DCS setup, you can always refer to readme.md file for how to clean up the lua files.

If you need more help, please do me a favor providing more details on how "you can't get it to work" (did you follow the instructions in the readme, or what error does the app throw at you etc)
Thanks for your interest in this project.

Jiutian
